const { autenticarUsuario, listarUsuarios, cadastrarUsuario } = require('../services/usersService');

module.exports.cadastrarUsuario = async (req, res) => {

    try {

        const payload = req.body;

        if (!payload || Object.keys(payload).length === 0) {

            console.warn(`\n(usersController.js): ${new Date()}: ‚ùó Requisi√ß√£o inv√°lida: corpo vazio.`);

            return res.status(400).json({
                success: false,
                message: 'O corpo da requisi√ß√£o est√° vazio ou mal formatado.'
            });

        }

        console.log(`\n(userssController.js): ${new Date()}: üìù Criando novo usu√°rio...`);

        const resultado = await cadastrarUsuario(payload);

        console.log(`\n(parametrosController.js): ${new Date()}: ‚úÖ Par√¢metro salvo com ID: ${resultado._id}`);

        return res.status(201).json({
            success: true,
            id: resultado._id,
            resultado: resultado
        });

    } catch (error) {

        console.error(`\n(parametrosController.js): ${new Date()}: ‚ùå Erro ao criar par√¢metro:`, error.message);

        return res.status(500).json({
            success: false,
            message: 'Erro interno ao salvar usu√°rio.'
        });

    }

};

module.exports.listarUsuarios = async (req, res) => {
    
    try {

        console.log(`\n(usersController.js): ${new Date()}: üì• Listando usu√°rios com filtros...`);

        // req.query pega os par√¢metros da URL (?userId=abc&permissions=admin)
        const filtros = req.query;

        const usuarios = await listarUsuarios(filtros);

        return res.status(200).json({
            success: true,
            total: usuarios.length,
            usuarios
        });

    } catch (error) {

        console.error(`\n(usersController.js): ${new Date()}: ‚ùå Erro ao listar usu√°rios:`, error.message);

        return res.status(500).json({
            success: false,
            message: 'Erro interno ao buscar usu√°rios.'
        });

    }

};

module.exports.autenticarUsuario = async (req, res) => {

    try {

        console.log(`\n(usersController.js): ${new Date()}: üì• Buscando lista de Usu√°rios...`);

        const body = req.body;
        const usuario = await autenticarUsuario(body.userId, body.password);

        res.json(usuario);

    } catch (error) {

        console.error(`\n(usersController.js): ${new Date()}: ‚ùå Erro ao autenticar usu√°rio:`, error.message);

        res.status(500).json({
            message: 'Erro interno ao autenticar usu√°rio.'
        });

    }

};